### ISSUE TITLE
Reorganize Map Algebra operations to match Tomlin structure

### ISSUE THREAD

**Issue by rcheetham** [geotrellis/geotrellis#1189]
From reviewing ops in:

https://github.com/geotrellis/geotrellis/tree/master/spark/src/main/scala/geotrellis/spark/op

There are several existing folders:
/elevation/
/focal/
/global/
/local/
/stats/
/zonal/

I'd like to suggest the following changes to the naming and file organization:
![map-algebra-function-types](https://cloud.githubusercontent.com/assets/595431/10568426/4f934f26-75e6-11e5-8770-322571396dab.png)
Diagram: Tomlin, 2015

This might involve the following steps:

1. Move Elevation operations to Focal - while hillshade is specific to elevation data, slope and aspect operations have broad usage beyond elevation data and are essentially focal operations (they fall within the "Focal Functions of Local Neighbors" in the above diagram)

2. Move current "Global" operations to Focal and consider renaming to FocalVisibility.  I'm not sure what "VerticalFlip" is but Viewshed is really a variation on focal operations and is part of a subset of Focal operations that use a neighborhood based on visibility (they fall within the "Focal Functions of Visible Neighbors" in the above diagram)

3. Consider organizing focal ops based on 4. sub-categories of operation:

**Comment by echeipesh** [comment]
I am addressing these code organizations in PR: https://github.com/geotrellis/geotrellis/pull/1323

Local and lateral focal operations are implemented with the same mechanism and are only distinguished by the value of the Neighborhood parameter. 

Slope and Aspect got moved to `geotrellis.raster.mapalgebra.focal`. However hillshade, while a focal operations, doesn't seem like map algebra since it is applied to specific domain, so it moves to `geotrellis.raster.elevation`

Cost distance and view shed as we implement them are not FocalVisibility. For FocalVisibility each cell of the output raster would have to be a function of cells reachable/visible from the focal cell. The cost distance we have produces reachability raster from a small set of points, so it deserves its own place in `geotrellis.raster.costdistance`. Likewise view shed algorithm produces view shed from a single point. This totally removes the `global` package from `geotrellis.raster.mapalgebra`.

An option exists to place view shed in `geotrellis.raster.elevation` with hillside, since they both appear to apply only to elevation data. It's not totally clear if view shed is special enough to preclude that grouping.

**Comment by rcheetham** [comment]
I said this in Slack, but both Hillshade and Visibility can be applied to
more than just actual elevation data, so I would argue for not grouping
them in elevation but, rather:

 Option 1: move Hillshade to Focal function - perhaps an
application-specific set of focal functions to which might be added Solar
Radiation, Imagery classification, Watershed, Flow Accumulation, Flow
Direction, etc. in the future.

 Option 2: some kind of application-specific grouping outside the
focal/local/zonal framework

Viewshed would be moved out of here if/when we implement a more generalized
FocalVisibility family of functions.

For cost distance, the Map Algebra way to handle this is with a
FocalAccessibility family of functions.  I think we could leave it as
"CostDistance" for now and deprecate later.  However, since we are breaking
everything now, it might also make sense to see how MrGEO organizes Cost
Distance functions as this is an area where they have a reputation for
having much more robust support.
