### ISSUE TITLE
Implement CGAlgorithms in geotrellis.vector

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1248]
JTS has functions in it's `CGAlgorithms`:
  - [ ] isPointInRing (RING)
  - [ ] isOnLine (LINE)
  - [ ] isCCW (RING)
  - [ ] distancePointLine (LINE)
  - [ ] distancePointLinePerpendicular (LINE)
  - [ ] distanceLineLine (LINE)

These should be implemented on `Point` and `Line` in geotrellis.vector, where appropriate. Part of this issue is tracking down exactly when these methods should be called on which types.

**Comment by dwins** [comment]
Looking into this a bit, I see that:
* isPointInRing should be called with a Point and a closed LineString.
* isOnLine should be called with a Point and any LineString (seems this is conceptually equivalent to linestring.contains(point) but I didn't look into the relative performance yet.)
* isCCW should be called with a valid ring (closed LineString that does not cross itself)
* distancePointLine should be called with a point and two more points defining a line segment (NOT a line string)
* distancePointLinePerpendicular should be called with a point and two more points defining an infinite line (still NOT a linestring)
* distanceLineLine should be called with exactly 4 points, two pairs defining line segments.

In order to express these constraints fully in the Scala type system I think it would appropriate to introduce a couple of new Geometry types - Segment for a line segment defined by only its start and end, and Ring for a LineString that is closed and does not self-intersect - both would produce a JTS LineString when asked for the jtsGeometry.  We could add asSegment: Option[Segment] and asRing: Option[Ring] to LineString to allow developers to convert.

**Comment by lossyrob** [comment]
Closed by #1255
