### ISSUE TITLE
Add option for specifying a max zoom level when ingesting raster images

### ISSUE THREAD

**Issue by mbertrand** [geotrellis/geotrellis#1484]
Currently, the max zoom level available for an ingested GeoTiff is determined by it's input resolution.  It would be nice to allow an option for manually specifying a maximum zoom level instead.

**Comment by lossyrob** [comment]
We would need to pass an optional config to this call, to specify the max zoom explicitly:

https://github.com/geotrellis/geotrellis/blob/36bfa97dbc23d27f94bcd312cbfc95a8815c0d66/spark-etl/src/main/scala/geotrellis/spark/etl/Etl.scala#L125

Here's inside that call, where it uses the scheme to find the zoom level:

https://github.com/geotrellis/geotrellis/blob/36bfa97dbc23d27f94bcd312cbfc95a8815c0d66/spark/src/main/scala/geotrellis/spark/TileLayerMetadata.scala#L162

https://github.com/geotrellis/geotrellis/blob/36bfa97dbc23d27f94bcd312cbfc95a8815c0d66/spark/src/main/scala/geotrellis/spark/TileLayerMetadata.scala#L173

The overload would have to manually put in the zoom level, so instead of using `levelFor` you would use `levelForZoom`

https://github.com/geotrellis/geotrellis/blob/36bfa97dbc23d27f94bcd312cbfc95a8815c0d66/spark/src/main/scala/geotrellis/spark/tiling/ZoomedLayoutScheme.scala#L92

However this means that this method would not work on the more general `LayoutScheme`, but work only on `ZoomedLayoutScheme`, which in practice is what you would want.

So really this change is about adding some overloads to `TileLayerMetadata.fromRdd`, and then calling it based on some configuration in the `Etl.tile` method.

**Comment by pomadchin** [comment]
Can be closed @lossyrob @echeipesh @rossbernet.
