### ISSUE TITLE
Alternative to .color(ColorMap) for transforming values

### ISSUE THREAD

**Issue by RickMohr** [geotrellis/geotrellis#1509]
It's useful to be able to transform raster values using a Scala `Map` which transforms input values to output values -- different from `.color(ColorMap)` in (at least) these ways:
- Control the output cell type (e.g. you could map doubles to doubles or doubles to ints)
- NODATA (as defined by the input cell type) maps to NODATA (as defined by the output cell type)

Ideally it would be available for both tiles and RDD's, and benefit from any optimizations implemented for #1489.

**Comment by fosskers** [comment]
Leaving a note here that #1489 was optimized by #1648 .

**Comment by fosskers** [comment]
@lossyrob there was talk in the standup this morning about tabling this issue until we've had a chance to really investigate `spire`. This would be fairly trivially solved with a polymorphic `Tile[T]`. If that doesn't end up working, I'll go for the more manual route as originally planned.

**Comment by fosskers** [comment]
A discussion with @echeipesh revealed the following:

- My PR doesn't need to extend `Tile`'s API; conversion from `Int => Double` and `Double => Int` is already possible with proper use of `map` on a Floating tile, or `mapDouble` on an Integer tile.
- [Eugene's PR](https://github.com/geotrellis/geotrellis/pull/1766)  is actually what adresses @RickMohr 's intial desire to control the output cell type
- The Functional workflow one expects to be able to do is:

```scala
val t: Tile = ...
val f: Int => Int = ...
val newCellType: CellType = ...

t.map(f).convert(newCellType)
```
and indeed, this is already possible but not performant. If in the near future we implemented lazy Tile operation semantics, then this issue is solved for free, and no additional `map` overloads are necessary.

**Comment by fosskers** [comment]
#1760 has been merged, which addresses the general ability to efficiently map over a tile via a `Map` with arbitrary Int/Double targets and sources. 

Fine-grained control over `CellType` is forth-coming.
