### ISSUE TITLE
No main class detected when running ./sbt run from cloned geotrellis master branch

### ISSUE THREAD

**Issue by lillythomas** [geotrellis/geotrellis#1578]
Hi,

I am attempting to get geotrellis up and running.  As of now, I have java version 1.7.0_79, scala version 2.11.8, and spark 1.6.2 set up.  I successfully ran the landsat tutorial, yet when I try to run "./sbt run" in the cloned geotrellis master branch, I encounter these errors:

`Missing bintray credentials /Users/lilliannethomas/.bintray/.credentials. Some bintray features depend on this.
[info] Set current project to geotrellis (in build file:/Users/lilliannethomas/geotrellis/)
[warn] Credentials file /Users/lilliannethomas/.bintray/.credentials does not exist
java.lang.RuntimeException: No main class detected.
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last geotrellis/compile:run for the full output.
[error] (geotrellis/compile:run) No main class detected.
`

I want to have access to all of the geotrellis functionality, so having this run is crucial.  I greatly appreciate any help in diagnosing (and hopefully solving) this error.  

Thanks in advance,
Lilly

**Comment by lossyrob** [comment]
Hi @lillythomas,

The GeoTrellis codebase is not something you would "run", as an `./sbt run` command would do. The GeoTrellis codebase is made up of separate subprojects that contain the library functionality, which you would pull into your project and build an application with (the application being something you would either want to `./sbt run`, `spark-submit`, or run in some other way). The running of the landsat-tutorial is an example of a Scala project that pulls in GeoTrellis submodules as JARs off of Maven Central via SBT, and uses GeoTrellis functionality in a `Main` method which you can run through SBT.

What you can run through sbt against this repo is the unit tests, to show that the codebase is functioning properly. To do so, you'll have to change to a subproject to run those tests. For example, to run the spark unit tests, you would run `./sbt "project spark" test`.

Is there something specific that you're trying to do with GeoTrellis, that perhaps we could talk through?

Thanks,
Rob

**Comment by lillythomas** [comment]
Hi Rob,

Thank you so much for such a swift and detailed reply.  I now see that I had completely misunderstood the framework.  I ran the "project spark" test as you instructed above and all tests passed!  

To give you some context into how I would like to use GeoTrellis, I program primarily in python and am new to scala, spark, and hadoop.  In an ideal world, I would like to pull large raster datasets (format: geotiffs) and some vector data into the GeoTrellis framework on EC2 (or locally to start).  In terms of the processing, I would like to take advantage of the raster functionality native to GeoTrellis (i.e. "Split rasters into smaller tiles, and stitch tiles into larger rasters"), as well as find a way to wrap python code and execute it within the same Scala framework used by GeoTrellis.  

I apologize if that was a bit long-winded and confusing, but perhaps you might have some advice on the last part (wrapping in python code)?  

Thank you so much again for your help,
Lilly

**Comment by lossyrob** [comment]
Hey Lilly,

The python wrapping is on our roadmap, but we don't yet have a good option for writing python code and executing it on Spark via GeoTrellis. Sorry to not have a better answer there, but it's something we're looking to solve because a lot of people want that feature!

However, pulling large rasters into a distributed backend like HDFS, Accumulo, S3 or Cassandra is our bread and butter, and while it's quite a lot of layers to build an ingest that will actually do that on a deployed system, it's what we use GeoTrellis for mainly. One useful thing to look at, and which is a step beyond the landsat tutorial (well, a couple steps actually, in terms of complexity), is https://github.com/geotrellis/geotrellis-landsat-emr-demo. The README should have some good information. It's a lot of new technologies esp if your new to the Scala and Spark/Hadoop world, but hopefully that provides some good source material to help guide learning the domain.

Also, feel free to chat with the GeoTrellis team on gitter (http://gitter.im/geotrellis/geotrellis) to ping us with questions and talk through some concepts.

Let me know if that helps, or if there's more questions I can try to answer!

Cheers,
Rob

**Comment by pomadchin** [comment]
I believe this issue can be closed, and re-opened / or created some new (as API changed a lot) and discussed in our [gitter channel](https://gitter.im/geotrellis/geotrellis) @lossyrob @echeipesh @rossbernet .

**Comment by kunal0895** [comment]
Hello @lossyrob , I am trying to use the ETL ingest process, and I wish to ingest a geotiff file into a catalog from my local file system, I dont have Hadoop installed. I searched a lot on google, and the geotrellis documentation as well, but i cannot find the proper approach or a proper way to do so. Could u help me in that? I have scala, spark, and sbt installed.

**Comment by pomadchin** [comment]
Hi @kunal0895, basically you don't need hadoop to ingest tiles, the only thing you need is Spark; We have [chatta demo](https://github.com/pomadchin/geotrellis-chatta-demo/blob/feature/chattademo-update/) which ingests data into local fs: [input.json](https://github.com/pomadchin/geotrellis-chatta-demo/blob/feature/chattademo-update/geotrellis/conf/input.json) , [output.json](https://github.com/pomadchin/geotrellis-chatta-demo/blob/feature/chattademo-update/geotrellis/conf/input.json); [example of ingest script](https://github.com/pomadchin/geotrellis-chatta-demo/blob/feature/chattademo-update/geotrellis/ingest.sh).

Any questions you may have we can discuss in addition in our [gitter channel](https://gitter.im/geotrellis/geotrellis).

**Comment by kunal0895** [comment]
Okay great. Thanks a lot @pomadchin .
