### ISSUE TITLE
classBreaks doesn't ignore NODATA when RDD has IntConstantNoDataCellType

### ISSUE THREAD

**Issue by RickMohr** [geotrellis/geotrellis#1580]
I called `classBreaks` on 12 different `TileLayerRDD[SpatialKey]`s, with these celltypes:
- `IntConstantNoDataCellType` (8 RDDs)
- `UByteCellType` (1 RDD)
- `UByteUserDefinedNoDataCellType` (1 RDD)
- `FloatUserDefinedNoDataCellType` (2 RDDs)

For all 8 of the `IntConstantNoDataCellType` RDDs, the first break returned was -2147483648 (the NODATA value), even though the RDDs contain only positive integers and NODATA. For the other 4 RDDs the results looked correct.

In contrast, `classBreaksExactInt` correctly ignored NODATA values for all 12 RDD's.

An example failing RDD was loaded from https://console.aws.amazon.com/s3/home?region=us-east-1#&bucket=azavea-datahub&prefix=catalog/us-census-property-value-30m-epsg3857/

I tried to reproduce the problem more simply in the `sbt` console using an `IntArrayTile`, but it worked fine there.

**Comment by RickMohr** [comment]
Note: for OTM we are using `classBreaksExactInt` as a workaround, but being able to use `classBreaks` would be a performance boost.

**Comment by lossyrob** [comment]
@RickMohr looking at that layer, I'm seeing the following:

```scala
      val rdd = reader.read[SpatialKey, Tile, TileLayerMetadata[SpatialKey]](LayerId("us-census-property-value-30m-epsg3857", 3))
      assert(rdd.metadata.cellType == IntConstantNoDataCellType)
      val t = rdd.collect().head._2
      assert(t.cellType == IntUserDefinedNoDataCellType(0))
      var sum = 0
      t.foreachDouble { z => if(z == NODATA.toDouble) { sum += 1 } }
      assert(sum > 0)

```

I'm not sure how this layer was ingested, but it looks like the CellType on the tiles are not correct. The tile is holding Int.MinValues that are supposed to be NODATA, but since the tile data type is IntUserDefinedNoDataCellType(0), these values are interpreted as actual values in a `Double` scenario.

**Comment by RickMohr** [comment]
@lossyrob, that layer was ingested by [this job](https://github.com/azavea/azavea-data-hub/blob/master/etl/ingest/jobs/census-property-value.sh). `gdalinfo` on the source raster shows `Type=Int32` and `NoData=2147483647`. I see that the job wrongly specifies `cellType=int32` ... that should be removed, making the cellType `int32ud2147483647`.

It's still a mystery how any values of -2147483648 got in there.

**Comment by RickMohr** [comment]
The other failures come from an unrelated case, where the RDD is produced this way:
```
      val resultMetadata = rdd.metadata.copy(cellType = IntConstantNoDataCellType)
      val normalizer = ColorMap(aMap, ColorMap.Options(noDataColor = NODATA))
      val normalizedRdd = rdd.color(normalizer)
      // ...normalized RDD's combined in weighted overlay
      val weightedRdd = ContextRDD(weightedOverlay, resultMetadata)
      val breaks = weightedRdd.classBreaks(numBreaks)
```

That's a simplification of the actual code, which is [here](https://github.com/OpenTreeMap/otm-modeling/blob/develop/tile/src/main/scala/TileService.scala#L83-97) and [here](https://github.com/OpenTreeMap/otm-modeling/blob/develop/tile/src/main/scala/TileServiceLogic.scala#L44-71). Might be simplest to look at it together.

**Comment by lossyrob** [comment]
`val resultMetadata = rdd.metadata.copy(cellType = IntConstantNoDataCellType)`

This does not actually change anything about the tiles. Just corrupts the metadata.
If you want to change the type of an RDD, you have to do a convert: `rdd.convert(IntConstantNoDataCellType)`, and _then_ change the metadata to reflect the actual cell type.

**Comment by RickMohr** [comment]
I know. Note the line
```
val normalizedRdd = rdd.color(normalizer)
```
where `normalizer` is a `ColorMap` with `noDataColor = NODATA`. 

I believe that means the tiles of `normalizedRdd` should be compatible with `IntConstantNoDataCellType`.

**Comment by lossyrob** [comment]
https://github.com/geotrellis/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/render/ColorMap.scala#L167

```scala
val result = ArrayTile.empty(IntCellType, tile.cols, tile.rows)
```

Actually it works with `IntCellType`, which is where the problem is coming from. It changes to raw Int values, and your nodata color is painting in NODATA values, which are being interpreted as actual data when reading double values out of the tile.

**Comment by RickMohr** [comment]
That's why I did
```
      val resultMetadata = rdd.metadata.copy(cellType = IntConstantNoDataCellType)
      val weightedRdd = ContextRDD(weightedOverlay, resultMetadata)
```
Since the output of `color` is integers with no NODATA handling, shouldn't assigning `IntConstantNoDataCellType` via the metadata cause it to treat the NODATA values as NODATA?

And you say "reading double values out of the tile". Why do you think they are double values?

**Comment by lossyrob** [comment]
Changing the layer-level metadata has no effect on the tiles. That `ContextRDD` call just couples the metadata to the RDD, it does not do any operations to the elements of that RDD. So you're calling the layer `IntConstantNoDataCellType`, but all of the tiles in the RDD are actually `IntCellType` (raw)). In order for the actual elements of the tile to be treated as `IntConstantNoDataCellType`, you would have to do `normalizedRdd.convert(IntConstantNoDataCellType)`.

I say "reading double values" because when you call `classBreaks`, it calls `histogram` on an RDD, which evaluates to a `histogramDouble` call (since the streaming histogram works on double values). That boils down to calling something like `tile.getDouble` on the tile; this gives a double no matter what the backing type of the tile is. In the case of an `IntConstantNoDataCellType`, the `getDouble` call would recognize that the value of the raster at that cell is a NoData value, and convert it to `Double.NaN`. In a `IntCellType` tile, it doesn't care that it equals NODATA (Int.MinValue), it doesn't consider anything to be a NoData value, so it passes it along via a `.toDouble` call, so we get the double representation of the NODATA value (`Int.MinValue.toDouble`), which is being counted as a valid value in the streaming histogram.

**Comment by pomadchin** [comment]
So that was a discussion about `classBreaks` usage, potentially we can add this information into docs.

**Comment by pomadchin** [comment]
@RickMohr is it more clear from the following https://github.com/geotrellis/geotrellis/blob/docs-overhaul/docs/guide/faq.md#how-can-i-convert-a-tiles-celltype how to work with Tile types? o:

**Comment by pomadchin** [comment]
@lossyrob However i believe it can be closed.
