### ISSUE TITLE
OSM => VectorTiles :: (5) Compacting RDD[(SpatialKey, Seq[Feature[G,D]]] to RDD[(SpatialKey, VectorTile)]

### ISSUE THREAD

**Issue by fosskers** [geotrellis/geotrellis#1661]
*This is Part 5 of a series of issues documenting the process of creating a world's worth of VectorTiles from OSM Planet data. Please use these issues to discuss solutions.*

**Question:** If you know all the geometries to pack into a single `VectorTile`, how do you best separate them into VT `Layer`s? Should Layers be distinguished by OSM tags?

**Comment by fosskers** [comment]
Consider the Cartography used by: https://github.com/omniscale/imposm3

**Comment by lossyrob** [comment]
To call it out explicitly, we're looking to construct vector tiles in such a way that would avoid any cartography IP conflicts such as this: https://github.com/osm2vectortiles/osm2vectortiles/issues/387

**Comment by drew-bower** [comment]
@rmrice   Here is the referenced issue.  Please track.

**Comment by rmrice** [comment]
So my understanding of the IP conflict was that osm2vectortiles was using the exact schema of Mapbox Streets in order to be compatible with Mapbox's OSM Bright style, which wasn't intended for use with non-Mapbox products. From the looks of it, they essentially [copied a yml file](https://github.com/stirringhalo/osm2vectortiles/commit/bcc7b6d80e3e2fb2376938ff5e4523566446f316) from Mapbox to serve as their schema, which has been deemed a problem.

I am in favor of creating a new schema based off [imposm3](https://github.com/omniscale/imposm3/blob/master/mapping/test_mapping.yml) that includes all osm features that might be rendered. The imposm3 schema makes the most sense from a cartography standpoint since each table generated would represent a layer in the tileset, and would advocate easy stylesheet creation using CartoCSS. The tables/layers based off this schema would be based of osm keys (landuse, highway, aeroway, water, etc.) with some keys coalesced into one table (so for example the landuse table would include values under keys landuse, amenity, historical, etc.). It would be worth it to go through the imposm3 mapping.yml and identify features that aren't included or any additional layers that would be beneficial. From looking through it a couple of times I noticed that there is only one military feature (military=barracks) and no historical features, which should be included in this new schema we're generating. We would also need to include additional layers for different types of labels (one for roads, one for places, etc.). 

Alternatively, I have created a schema in Tilemill (for export as a Mapnik XML) that queries features from an osm database to create layers, which would essentially be the same thing as what we would create using a yml file for vector tiles. The layers I generated for this Mapnik xml style are based on osm keys (landuse, highway, aeroway, water, etc.) with some keys coalesced into one table (like amenity, historical, cultural, and landuse features coalesced into `'type'` for table `landuse`), and includes pretty much anything you might want to render. The only difference is it is querying data from a database created using osm2pgsql rather than imposm. But this could be used to help create a new vector tile schema.

**Comment by fosskers** [comment]
@rmrice That yml file hasn't been removed in master, it seems.

**Comment by fosskers** [comment]
Our plan is to avoid ingestion into a database entirely. @rmrice is your schema something that can be referenced statically to write code off it, or does it necessitate using a DB?

**Comment by lossyrob** [comment]
@rmrice great comments, I believe that line of thinking is where we're going.

It seems like what we need in our case is a way to take a `yml` file, which currently is used to specify schema as either DB tables or vector tiles, and use it in our ingest step to bake these vector tiles. @fosskers I would imagine that this could be wrapped up in some combineByKey step, where vector tiles are build in a streaming way based on some configuration object we derive from this type of yml.

It doesn't seem like the YML for specifying schema is read in a standard way, and also seems to include SQL for some configs; we'd have to figure out a way to specify generic schemas in our processes that match what we need, which doesn't involve SQL queries. I vote keeping YAML just because it seems like that's what the community is used to specifying schemas as.

I will have to look deeper into what imposm3's schema looks, and it would be useful to compare it to other schemas out there. This may be better on the osm2vectortiles ticket (or somewhere we can collaboratively decide on an open OSM schema), but what I'd really like to be able to see is a comparison of all the open schemas currently out there...mapzen's, imposm3's, carto basemaps, and more (tbh I don't understand the field enough to even make a pseudo-comprehensive list). From that we can sort of derive what the current common pieces are out there that should definitely be included, and work to resolve differences by either picking the best, or figuring out how to make aspects of the schema satisfy each of the reasons that those differences exist. @rmrice seems like you know the field better than us, do you have any suggestions on how to accomplish this?

@fosskers it's my understanding that the imposm3 "schema" represents the set of tables that it ingests the vector data into, and what tags it places under what names, and those would roughly correspond to the layers and metadata of vectortiles. Someone please correct me if I'm wrong about that.

**Comment by lossyrob** [comment]
Here is documentation of Mapzen's tile schema: https://mapzen.com/documentation/vector-tiles/layers/

**Comment by rmrice** [comment]
@fosskers the schema I'm using right now relies on a database that was ingested using osm2pgsql, but results in a package of layers that include all the features we want. I was mostly suggesting that if we do need to query data, I can offer up the queries I'm currently using to use as a base, but if we're avoiding SQL then that probably won't be necessary.

@lossyrob to my knowledge your understanding of the imposm3 schema is correct. It's just a different way to organize OSM features in a database. Rather than sticking all features of one geometry type (point, line, polygon) into the same table, it separates them further to create a table for each OSM key. If an imposm3 database is transformed into vector tiles, it would then result in a layer for each table, or each OSM key (or at least that's how it worked when I was experimenting with tippecanoe>>mbtiles). 

I don't think there are too many open schemas out there besides the ones you mentioned, and they are all organized very similarly based off the imposm3 outline. I would like to come up with a schema that includes any feature that might want to be rendered, I'm just not sure how to do this for custom tags. The problem with Mapbox's vector tile schema is that it's pretty watered-down in terms of what feature tags are included. It includes all of the necessary features, which simplifies stylesheet creation for general feature maps, but excludes a lot of features too, which is a problem when creating a cartographic product for certain use cases, and is not very useful for what I am working on here at DG (hence why I want a vector tile set that includes all features :smile: ). Their picking and choosing of which features to include in their schema is their IP, and I don't think we'll have to worry about colliding with that if we include more stuff.

Tagging @Cellington1 because he has done quite a bit of research on vector tiles and might have some insight into creating a schema. And I do think we all agree that ymls are the way to go :+1:

**Comment by fosskers** [comment]
@rmrice We're confident we can see significant performance increases by avoiding a database, yeah. 

> it separates them further to create a table for each OSM key ... it would then result in a layer for each table

A layer per key makes sense. Some general questions:

1. Do we have a master list of de-facto standard keys? [Is this it?](http://wiki.openstreetmap.org/wiki/Map_Features) 
2. Should all VTs have the same layers, even if a particular Tile has no Elements of a particular tag? Example: a tile of all forest having an empty `highway` layer, for conformity.
3. If (2), do we draw a line in the sand for which keys are blessed as standard? If not, (2)'s natural conclusion is for all tiles to have a layer per key that appears anywhere in the world, even if its custom and only appears once.

 While still a work-in-progress, [this PR](https://github.com/geotrellis/geotrellis/pull/1663) addresses the creation of lossless (in terms of tag information) GeoTrellis Features from OSM Elements. Our current thought is to have a store of "lossless" VTs with all tag data and layers intact, which can then have a `.yml`-based schema applied to them dynamically for "render-only" VTs, or whatever other kind a user could want.

**Comment by fosskers** [comment]
This discussion has moved here: https://github.com/geotrellis/vectorpipe/issues/5
