### ISSUE TITLE
Allow ETL (and tile RDD reprojection) to target specific zoom level

### ISSUE THREAD

**Issue by lossyrob** [geotrellis/geotrellis#1717]
We want to allow the user to define a specific zoom level to target in ETL. This requires the change to allow a target zoom in tile rdd reprojection, since it by default takes the zoom level of the target scheme (or 0 for passing in a specific layout definition). For instance, a user might be ingesting a layer that geotrellis determines to be zoom 15, but they want to save off the layer to zoom 16 to match other layers in their catalog.

**Comment by pomadchin** [comment]
@lossyrob does it mean pyramiding down?

**Comment by lossyrob** [comment]
Potentially, yes

**Comment by echeipesh** [comment]
Let me attempt to reframe this issue: The real problem is that when working with mixed resolution layers in a pyramid we can only work on levels they share, otherwise the keys don't line up.

Pyramiding down is A solution to this, but it's a bad one. Going down takes 4x as much space of each previous layer and you don't get any new information, you're just saving the results of a dynamic resample.

Better solution is to resample layers on the fly to the required zoom. The I/O costs will be much lower and the additional CPU cost should not even come close to offsetting the I/O savings.

We already have `TileLayerRDD.resampleToZoom`: https://github.com/geotrellis/geotrellis/blob/2e871993bbb76f407da760cbf59a7e805ce7c375/spark/src/main/scala/geotrellis/spark/resample/ZoomResample.scala

Maybe we need a reader that wraps a reader and resamples for layers that don't exist. I like that pattern because it will allow us to stack Reader effects (We were planning to handle meta-tiling in a similar manner)

**Comment by pomadchin** [comment]
Agree with @echeipesh ; and `Pyramid.down` function is really _**not the best solution**_ ~ already implemented a prototype

**Comment by pomadchin** [comment]
`maxZoom` option works as expected

**Comment by pomadchin** [comment]
We already supported that feature :) `maxZoom` etl option.
